apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "sample-dotnet-app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "sample-dotnet-app.name" . }}
    helm.sh/chart: {{ include "sample-dotnet-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "sample-dotnet-app.name" . }}
          servicePort: {{ .Values.service.port }}