# Default values for sample-dotnet-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  version: changeme

image:
  repository: saharshsingh/sample-dotnet-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  host: sample-dotnet-app-sample-projects-dev.192.168.99.100.nip.io

env:
  valuesServiceType: simple
